### ISSUE TITLE
Drag-N-Drop Image upload workflow

### ISSUE THREAD

**Issue by newburns** [gadlol/alternative-administration-system#6]
It is hard to understand what the AAS is doing after an image upload from the product view. If you drag and drop an image, you must close out of the uploader. There is no status of the upload, so it is not clear when to close out. The upload seems to happen in the background, but the image does not show until a refresh

*NOTE: MAY NOT BE A BUG
Also, the uploader does not work  well with the KISSit addon. The image name overwrites other image names, causing images to replace other product images.

**Comment by gadlol** [comment]
Images drag n drop have been updated for v0.3.
If there is a duplicate image AAS can rewrite it or auto rename it or break uploading process. Its up your choice.
